// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    PanCode: typeof import('./components/PanCode.vue')['default']
    PanDrawer: typeof import('./components/PanDrawer.vue')['default']
    PanForm: typeof import('./components/PanForm.vue')['default']
    PanFormItem: typeof import('./components/PanFormItem.vue')['default']
    PanInput: typeof import('./components/PanInput.vue')['default']
    PanModal: typeof import('./components/PanModal.vue')['default']
    PanSwiper: typeof import('./components/PanSwiper.vue')['default']
    PanSwiperItem: typeof import('./components/PanSwiperItem.vue')['default']
    PanUpload: typeof import('./components/PanUpload.vue')['default']
    README: typeof import('./components/README.md')['default']
    Record: typeof import('./components/Record.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
